version: '3'

services:

  distributed_cache:
    image: redis
    ports:
    - 5551:6739

  messages_middleware:
    image: rabbitmq
    ports:
    - 5552:5672

  tracking:
    image: tracking
    build:
      context: .
      dockerfile: Tracking/Dockerfile

  vehicle:
    image: vehicle
    build:
      context: .
      dockerfile: Vehicle/Dockerfile

  customer:
    image: customer
    build:
      context: .
      dockerfile: Customer/Dockerfile

  ping:
    image: ping
    build:
      context: .
      dockerfile: Ping/Dockerfile

